-- Métricas del modo nocturno y del reporte semanal (garantía de 7 días).
-- Idempotente: se puede ejecutar más de una vez. Ejecutar después de 20260926_create_follow_ups.sql.
-- Si aún no se ejecuta, el bot sigue funcionando: solo no guarda estas métricas.

-- Citas: pedidas con la clínica cerrada, cuándo recepción la confirmó y si el paciente la reprogramó.
ALTER TABLE IF EXISTS public.appointments ADD COLUMN IF NOT EXISTS after_hours BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE IF EXISTS public.appointments ADD COLUMN IF NOT EXISTS confirmed_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS public.appointments ADD COLUMN IF NOT EXISTS rescheduled_at TIMESTAMPTZ;

-- Leads: primer contacto con la clínica cerrada.
ALTER TABLE IF EXISTS public.leads ADD COLUMN IF NOT EXISTS after_hours BOOLEAN;

-- Conversaciones: primer mensaje del paciente y tiempo hasta la primera respuesta del bot.
ALTER TABLE IF EXISTS public.conversations ADD COLUMN IF NOT EXISTS first_message_at TIMESTAMPTZ;
ALTER TABLE IF EXISTS public.conversations ADD COLUMN IF NOT EXISTS first_response_ms INTEGER;
ALTER TABLE IF EXISTS public.conversations ADD COLUMN IF NOT EXISTS after_hours BOOLEAN;

-- Pases a humano (urgencias clínicas y pedidos de hablar con una persona).
CREATE TABLE IF NOT EXISTS public.handoffs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id TEXT NOT NULL,
  phone TEXT NOT NULL,
  reason TEXT NOT NULL CHECK (reason IN ('urgencia', 'humano')),
  after_hours BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS handoffs_clinic_created_idx ON public.handoffs (clinic_id, created_at);
ALTER TABLE public.handoffs ENABLE ROW LEVEL SECURITY;

-- Consultas del reporte por rango de fechas.
DO $$
BEGIN
  IF to_regclass('public.conversations') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS conversations_first_message_at_idx ON public.conversations (first_message_at);
  END IF;
END $$;
