-- Conversations schema used by the WhatsApp webhook and monitor panel.
-- Idempotent so it can repair an existing table missing contact_number.

CREATE TABLE IF NOT EXISTS public.conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id TEXT NOT NULL,
  contact_number TEXT,
  phone TEXT NOT NULL,
  contact_name TEXT,
  last_message TEXT,
  last_message_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  status TEXT NOT NULL DEFAULT 'active'
);

ALTER TABLE public.conversations
  ADD COLUMN IF NOT EXISTS conversation_id TEXT,
  ADD COLUMN IF NOT EXISTS contact_number TEXT,
  ADD COLUMN IF NOT EXISTS phone TEXT,
  ADD COLUMN IF NOT EXISTS contact_name TEXT,
  ADD COLUMN IF NOT EXISTS last_message TEXT,
  ADD COLUMN IF NOT EXISTS last_message_at TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'active';

-- Existing rows must have a key before enforcing the webhook's upsert contract.
UPDATE public.conversations
SET conversation_id = COALESCE(NULLIF(conversation_id, ''), contact_number, phone, id::TEXT),
   phone = COALESCE(NULLIF(phone, ''), contact_number, conversation_id, id::TEXT)
WHERE conversation_id IS NULL OR conversation_id = '' OR phone IS NULL OR phone = '';

UPDATE public.conversations
SET status = COALESCE(NULLIF(status, ''), 'active')
WHERE status IS NULL OR status = '';

ALTER TABLE public.conversations
  ALTER COLUMN conversation_id SET NOT NULL,
  ALTER COLUMN phone SET NOT NULL,
  ALTER COLUMN last_message_at SET DEFAULT NOW(),
  ALTER COLUMN created_at SET DEFAULT NOW(),
  ALTER COLUMN updated_at SET DEFAULT NOW();

-- Keep one row per conversation before creating the unique key required by upsert.
WITH duplicates AS (
  SELECT ctid,
         ROW_NUMBER() OVER (PARTITION BY conversation_id ORDER BY created_at NULLS LAST, ctid) AS row_number
  FROM public.conversations
)
DELETE FROM public.conversations AS c
USING duplicates AS d
WHERE c.ctid = d.ctid
  AND d.row_number > 1;

CREATE UNIQUE INDEX IF NOT EXISTS conversations_conversation_id_key
  ON public.conversations (conversation_id);

CREATE INDEX IF NOT EXISTS conversations_last_message_at_idx
  ON public.conversations (last_message_at DESC);

CREATE INDEX IF NOT EXISTS conversations_contact_number_idx
  ON public.conversations (contact_number);
