-- Seguimiento único a leads que no agendaron (POST /jobs/follow-ups).
-- Idempotente. Ejecutar después de 20260925_create_appointments.sql.

CREATE TABLE IF NOT EXISTS public.follow_ups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id TEXT NOT NULL,
  phone TEXT NOT NULL,
  sent_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Un solo mensaje de retoma por paciente y clínica, aunque el cron se ejecute varias veces.
CREATE UNIQUE INDEX IF NOT EXISTS follow_ups_clinic_phone_uidx ON public.follow_ups (clinic_id, phone);

ALTER TABLE public.follow_ups ENABLE ROW LEVEL SECURITY;

-- Consultas de los jobs sobre mensajes entrantes (resumen diario y seguimiento).
DO $$
BEGIN
  IF to_regclass('public.messages') IS NOT NULL THEN
    CREATE INDEX IF NOT EXISTS messages_role_created_at_idx ON public.messages (role, created_at);
    CREATE INDEX IF NOT EXISTS messages_phone_created_at_idx ON public.messages (phone, created_at DESC);
  END IF;
END $$;
