-- Configuración editable desde el panel (pestaña ⚙️ Configuración, solo el dueño). Idempotente.
-- config/clinics/<id>.js son los valores base; aquí se guardan solo los cambios (overrides) y la
-- auditoría de cada cambio. RLS activo y sin políticas: solo el servidor (service role) puede leer o escribir.
-- Las fotos van al bucket de Storage "clinic-media" (el servidor lo crea solo si no existe).

CREATE TABLE IF NOT EXISTS public.clinic_settings (
  clinic_id TEXT PRIMARY KEY,
  data JSONB NOT NULL DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by TEXT
);
ALTER TABLE public.clinic_settings ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.clinic_settings_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id TEXT NOT NULL,
  changed_by TEXT,
  field TEXT NOT NULL,
  before JSONB,
  after JSONB,
  changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS clinic_settings_audit_clinic_idx ON public.clinic_settings_audit (clinic_id, changed_at DESC);
ALTER TABLE public.clinic_settings_audit ENABLE ROW LEVEL SECURITY;
