-- Conversations schema used by the WhatsApp webhook and monitor panel.
-- Idempotent so it can repair an existing table missing contact_number.

CREATE TABLE IF NOT EXISTS public.conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id TEXT NOT NULL,
  contact_number TEXT,
  contact_name TEXT,
  last_message TEXT,
  last_message_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.conversations
  ADD COLUMN IF NOT EXISTS conversation_id TEXT,
  ADD COLUMN IF NOT EXISTS contact_number TEXT,
  ADD COLUMN IF NOT EXISTS contact_name TEXT,
  ADD COLUMN IF NOT EXISTS last_message TEXT,
  ADD COLUMN IF NOT EXISTS last_message_at TIMESTAMPTZ DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

-- Existing rows must have a key before enforcing the webhook's upsert contract.
UPDATE public.conversations
SET conversation_id = COALESCE(NULLIF(conversation_id, ''), contact_number, id::TEXT)
WHERE conversation_id IS NULL OR conversation_id = '';

ALTER TABLE public.conversations
  ALTER COLUMN conversation_id SET NOT NULL,
  ALTER COLUMN last_message_at SET DEFAULT NOW(),
  ALTER COLUMN created_at SET DEFAULT NOW();

CREATE UNIQUE INDEX IF NOT EXISTS conversations_conversation_id_key
  ON public.conversations (conversation_id);

CREATE INDEX IF NOT EXISTS conversations_last_message_at_idx
  ON public.conversations (last_message_at DESC);

CREATE INDEX IF NOT EXISTS conversations_contact_number_idx
  ON public.conversations (contact_number);
