-- Tablas base del bot (leads, mensajes y clínicas) para un proyecto de Supabase NUEVO.
-- Idempotente: en un proyecto que ya las tiene no cambia nada (CREATE TABLE IF NOT EXISTS).
-- Ejecutar primero; después, el resto de migrations/ en orden de fecha.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Un lead por teléfono (9 dígitos). leadService hace upsert por "telefono".
CREATE TABLE IF NOT EXISTS public.leads (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  telefono TEXT NOT NULL,
  nombre TEXT,
  distrito TEXT,
  clinic_id TEXT,
  fecha_hora_texto TEXT,
  fecha_hora_iso TIMESTAMPTZ,
  ready_to_notify BOOLEAN NOT NULL DEFAULT FALSE,
  notified_at TIMESTAMPTZ,
  lead_snapshot JSONB,
  ad_referral JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS leads_telefono_uidx ON public.leads (telefono);
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Cada mensaje entrante (role = 'user') y saliente (role = 'assistant').
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone TEXT NOT NULL,
  from_phone TEXT,
  role TEXT NOT NULL,
  content TEXT,
  whatsapp_message_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS messages_phone_created_at_idx ON public.messages (phone, created_at DESC);
CREATE INDEX IF NOT EXISTS messages_role_created_at_idx ON public.messages (role, created_at);
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Opcional: datos de la clínica por número de WhatsApp Business. Si no hay fila, se usa
-- config/clinics/<ACTIVE_CLINIC>.js (lo normal). Existe para que la consulta no falle.
CREATE TABLE IF NOT EXISTS public.clinics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT,
  address TEXT,
  schedule TEXT,
  waba_phone_number_id TEXT UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
ALTER TABLE public.clinics ENABLE ROW LEVEL SECURITY;

-- Si las tablas ya existían (proyecto anterior), se agregan las columnas que el bot usa y falten.
ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS nombre TEXT,
  ADD COLUMN IF NOT EXISTS distrito TEXT,
  ADD COLUMN IF NOT EXISTS clinic_id TEXT,
  ADD COLUMN IF NOT EXISTS fecha_hora_texto TEXT,
  ADD COLUMN IF NOT EXISTS fecha_hora_iso TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS ready_to_notify BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS notified_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS lead_snapshot JSONB,
  ADD COLUMN IF NOT EXISTS ad_referral JSONB,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

ALTER TABLE public.messages
  ADD COLUMN IF NOT EXISTS from_phone TEXT,
  ADD COLUMN IF NOT EXISTS content TEXT,
  ADD COLUMN IF NOT EXISTS whatsapp_message_id TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
